# Generated by Django 5.1.3 on 2024-11-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomApp', '0002_alter_showroom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
