# Generated by Django 5.1.3 on 2024-11-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowRoomApp', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
